FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

#install the packages
RUN yarn

EXPOSE 80


COPY . .

CMD ['yarn', "start"]


